import { Search } from 'lucide-react';
import { listAuditLogs, listBusinesses } from '@/services/super-admin/admin-data.server';
import { PageHeader } from '@/components/super-admin/page-header';
import { Card } from '@/components/super-admin/ui/card';
import { Button } from '@/components/super-admin/ui/button';
import { EmptyState, ErrorState } from '@/components/super-admin/ui/states';
import { formatDate } from '@/lib/super-admin/utils';

export default async function AuditLogsPage({ searchParams }: { searchParams: Promise<{ search?: string; business?: string; module?: string; user?: string; action?: string; from?: string; to?: string }> }) {
  const params = await searchParams;
  try {
    const [logs, businesses] = await Promise.all([listAuditLogs({ search: params.search, businessId: params.business, module: params.module, user: params.user, action: params.action, from: params.from, to: params.to }), listBusinesses({ pageSize: 500 })]);
    const modules = [...new Set(logs.map((item) => item.entityType))].sort();
    return <div className="space-y-6"><PageHeader title="Audit Logs" description="Review actions performed across businesses, users, and platform modules." /><Card><form className="grid gap-3 border-b border-slate-200 p-4 md:grid-cols-2 xl:grid-cols-4 dark:border-slate-800"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input name="search" defaultValue={params.search} placeholder="Search descriptions" className="h-10 w-full rounded-md border border-slate-200 bg-white pl-9 pr-3 text-sm dark:border-slate-700 dark:bg-slate-950" /></label><select name="business" defaultValue={params.business} className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="">All Businesses</option>{businesses.rows.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="module" defaultValue={params.module} className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="">All Modules</option>{modules.map((item) => <option key={item}>{item}</option>)}</select><input name="user" defaultValue={params.user} placeholder="User" className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950" /><input name="action" defaultValue={params.action} placeholder="Action" className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950" /><input name="from" type="date" defaultValue={params.from} className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950" /><input name="to" type="date" defaultValue={params.to} className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950" /><Button type="submit">Apply Filters</Button></form>{logs.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-950"><tr>{['Timestamp','Business','User','Role','Module','Action','Description'].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{logs.map((log) => <tr key={log.id}><td className="whitespace-nowrap px-4 py-4">{formatDate(log.createdAt)}</td><td className="px-4 py-4 font-medium">{log.businessName}</td><td className="px-4 py-4">{log.userNameSnapshot}</td><td className="px-4 py-4">{log.roleSnapshot}</td><td className="px-4 py-4">{log.entityType}</td><td className="px-4 py-4 font-medium">{log.action.replaceAll('_',' ')}</td><td className="max-w-md px-4 py-4 text-slate-500">{log.description}</td></tr>)}</tbody></table></div> : <EmptyState title="No audit logs found" description="System activity will appear here when matching events are recorded." />}</Card></div>;
  } catch {
    return <ErrorState message="Unable to load audit logs. Confirm Supabase access policies." />;
  }
}
