import {
  Home,
  Package,
  ShoppingCart,
  Archive,
  Settings,
  BarChart3,
  ClipboardList,
  ShieldCheck,
  ScrollText,
  Users,
} from 'lucide-react';
import { NavItem } from '@/types/Navbar';

export const NAVBAR_ITEMS: NavItem[] = [
  {
    title: 'Dashboard',
    path: '/home',
    icon: <Home className="h-4 w-4" />,
    roles: ['OWNER', 'MANAGER'],
    moduleKey: 'dashboard',
  },
  {
    title: 'POS Billing',
    path: '/orders',
    icon: <ShoppingCart className="h-4 w-4" />,
    roles: ['OWNER', 'MANAGER', 'CASHIER'],
    moduleKey: 'pos_billing',
  },
  {
    title: 'Products',
    path: '/product',
    icon: <Package className="h-4 w-4" />,
    roles: ['OWNER', 'MANAGER'],
    moduleKey: 'products',
  },
  {
    title: 'Sales Records',
    path: '/records',
    icon: <Archive className="h-4 w-4" />,
    roles: ['OWNER', 'MANAGER', 'CASHIER'],
    moduleKey: 'sales_records',
  },
  {
    title: 'Customers',
    path: '/customers',
    icon: <Users className="h-4 w-4" />,
    roles: ['OWNER', 'MANAGER', 'CASHIER'],
    moduleKey: 'customers',
  },
  {
    title: 'Reports',
    path: '/analytics',
    icon: <BarChart3 className="h-4 w-4" />,
    roles: ['OWNER', 'MANAGER'],
    moduleKey: 'reports',
  },
  {
    title: 'Inventory Ledger',
    path: '/inventory',
    icon: <ClipboardList className="h-4 w-4" />,
    roles: ['OWNER', 'MANAGER'],
    moduleKey: 'inventory_ledger',
  },
  {
    title: 'Staff Management',
    path: '/staff',
    icon: <ShieldCheck className="h-4 w-4" />,
    roles: ['OWNER'],
    moduleKey: 'staff_management',
  },
  {
    title: 'Audit Logs',
    path: '/audit-logs',
    icon: <ScrollText className="h-4 w-4" />,
    roles: ['OWNER'],
    moduleKey: 'audit_logs',
  },
  {
    title: 'Business Settings',
    path: '/settings',
    icon: <Settings className="h-4 w-4" />,
    roles: ['OWNER'],
    moduleKey: 'business_settings',
  },
];
